version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/ubuntu/certs:/certs"
  # redis:
  #   image: "kingstonduo/cassiopeia-web:1.1"