import React, { Component } from 'react';

class Landing extends Component {
	
	
    render() {
        return (
            <div id="landing-page">
                <div className="row justify-content-center">
                    <h5>WHAT IS THE PARTICIPANT PORTAL?</h5>
                </div>
                <div className="row justify-content-center my-3">
                    <h3>The KPMP Participant Portal gives study participants access to their <br/>
                    data that is generated by the scientists from the KPMP consortium.</h3>
                </div>
                <div className="row justify-content-center">
                    <img src="/img/landing/figure_data-portal-flow.svg" alt="KPMP Data flow diagram"/>
                </div>
            </div>
        )
    }
}

export default Landing;