const actionNames = {
    SET_SELECTED_PATIENT: "SET_SELECTED_PATIENT",
    GET_PATIENT_SLIDES: "GET_PATIENT_SLIDES",
    SET_SELECTED_SLIDE: "SET_SELECTED_SLIDE",
    SET_LOGGED_IN: "SET_LOGGED_IN",
};

export default actionNames;